# Generated by Django 3.2 on 2022-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsavailable',
            name='from_coins',
            field=models.CharField(blank=True, choices=[('EUA', 'Euro'), ('USD', 'Dolar'), ('BRL', 'Real'), ('GBP', 'Libra')], max_length=10, null=True),
        ),
    ]
