# Generated by Django 3.2 on 2022-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220228_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsavailable',
            name='from_coins',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real'), ('GBP', 'Libra'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coinsavailable',
            name='to_coins',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'Dólar'), ('BRL', 'Real'), ('GBP', 'Libra'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=10, null=True),
        ),
    ]
